package:
  name: neuralcoref
  version: "2.0"

source:
  path: /home/craft-3/repos/neuralcoref

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - spacy
    - falcon
    - pathlib
    - python-mimeparse
 
test:
  imports:
    - neuralcoref

about:
  home: /home/craft-3/repos/neuralcoref
  license: BSD
